### ISSUE TITLE
Errors reported by plugin when an empty VS Code window is opened.

### ISSUE THREAD

**Issue by adrianffletcher** [accordproject/ergo-vscode-plugin#24]
When a new empty window is created in VS Code the following error message is displayed: "The Cicero server crashed 5 times in the last 3 minutes. The server will not be restarted."

<img width="536" alt="Screen Shot 2019-06-28 at 12 19 22" src="https://user-images.githubusercontent.com/29235349/60338933-2cae9700-999f-11e9-800d-da4c4216d94c.png">

[Kapture 2019-06-28 at 12.16.54.mp4.zip](https://github.com/accordproject/ergo-vscode-plugin/files/3338941/Kapture.2019-06-28.at.12.16.54.mp4.zip)

**Comment by dselman** [comment]
Please create issues with the new VSCode extension here: https://github.com/accordproject/cicero-vscode-extension/issues
